settings:
  application:
    domain: localhost:8000
    host: 0.0.0.0
    ishttps: false
    mode: dev
    name: testApp
    port: "8000"
    readtimeout: 1
    writertimeout: 2
  database:
    dbtype: mysql
    host: 182.92.201.22
    name: go_admin
    password: dnjDWmMX4Ac6NWmD
    port: 3306
    username: go_admin
  jwt:
    secret: go-admin
    timeout: 3600
  log:
    dir: temp/logs
    operdb: false
  ssl:
    key: keystring
    pem: temp/pem.pem
